### Create Article
POST localhost:8080/api/v1/article
Content-Type:  application/json
Authorization: Basic YWRtaW46MTIzNDU=

{
  "title": "Valish",
  "description": "Aliyev",
  "content": "Aliyev",
  "imageId": "dasad-sdasda-sdasda-asdasd",
  "regionId": 1,
  "categoryId": 1,
  "articleType": [1,2,3,4,5]
}


### Update Article
POST localhost:8080/api/v1/article/aaa-bbb-ccc-ddd
Content-Type:  application/json
Authorization: Basic YWRtaW46MTIzNDU=

{
  "title": "Valish",
  "description": "Aliyev",
  "content": "Aliyev",
  "imageId": "dasad-sdasda-sdasda-asdasd",
  "regionId": 1,
  "categoryId": 1,
  "articleType": [1,2,7,8]
}

### Delete Article
DELETE localhost:8080/api/v1/article/aaaa-vvvv-dddd-ssss
Authorization: Basic YWRtaW46MTIzNDU=


### change status
POST localhost:8080/api/v1/article/aaa-bbb-ccc-ddd
Content-Type:  application/json
Authorization: Basic YWRtaW46MTIzNDU=

{
  "status": "PUBLISHED"
}

### get last 5
GET localhost:8080/api/v1/article/get5



