### login
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "phone": "1212",
  "password": "1234"
}

### Registration
POST localhost:8080/api/v1/auth/registration
Content-Type:  application/json

{ "name": "Temur",
  "surname": "chort",
  "email": "uytvbox2008@gmail.com",
  "password": "12345"
}