### Create student
POST localhost:8080/api/v1/category
Content-Type: application/json
Authorization: Basic YWRtaW46MTIzNDU=


{
  "orderNum": 1,
  "nameUz": "Samarqand",
  "nameRu": "Самарканд",
  "nameEn": "Samarqand"
}


### Update by id
PUT localhost:8080/api/v1/category/1
Content-Type: application/json
Authorization: Basic YWRtaW46MTIzNDU=


{
  "orderNum": 1,
  "nameUz": "Toshkent",
  "nameRu": "Ташкент",
  "nameEn": "Tashkent"
}


### Get all
GET localhost:8080/api/v1/category/all
Authorization: Basic YWRtaW46MTIzNDU=


