### Create student
POST localhost:8080//api/v1/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTA0NTExNjYsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2OTA0NTQ3NjYsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.plGv7aM4vFz-OlyojjTChF73v7WzdqjmToHROw5Ynau0phAUTijYqasKPokqjwjGLQ-z53cc7fmC-FVU1Av8XQ

{
  "name": "alijon",
  "surname": "alijonov",
  "email": "alijon@gmail.com",
  "phone": "1212",
  "password": "1234",
  "role": "MODERATOR"
}

### Update by id
PUT localhost:8080/api/v1/profile/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTA0Mzg1NzMsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2OTA0NDIxNzMsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.E2pDgVHld3N1_-3OkWBcxD3nUwvfmKDygpUPxNkMUoWUJv8sfx7ZpLtYNrWPFQ11HcFt-070aPaXyvj9LJeG9A

{
  "name": "aLI",
  "surname": "aLIYEV"
}

###Get
GET localhost:8080/api/v1/profile/get
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2OTA0Mzg1NzMsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2OTA0NDIxNzMsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.E2pDgVHld3N1_-3OkWBcxD3nUwvfmKDygpUPxNkMUoWUJv8sfx7ZpLtYNrWPFQ11HcFt-070aPaXyvj9LJeG9A



