### Create student
POST localhost:8080//api/v1/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk4NjcwODQsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk4NzA2ODQsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.tNh3AKfBkmBPtxM3EzlzIFQ9DLJbDRgaj-sm9EXWUE2Bo2sCCZWTGGUJHIjY3nRDBgkPLXFHFkRGfJaLkVfPLQ

{
  "name": "alijon",
  "surname": "alijonov",
  "email": "alijon@gmail.com",
  "phone": "1212",
  "password": "1234",
  "role": "USER"
}

### Update by id
PUT localhost:8080/profile/simple/1
Content-Type: application/json

{
  "name": "aLI",
  "surname": "aLIYEV"
}

### Update by id
GET localhost:8080/api/v1/profile/detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODk2MTc4NzUsImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODk2MjE0NzUsImlzcyI6Imt1bnV6IHRlc3QgcG9ydGFsaSJ9.-CkDWmjz8aT-gaTrWhpmvlsmhTCwuyapPSfLCq03uVcTUHRFTmfKiRr3I2VZwYBoadE5qeselA_NoW-ZcsyBiw

{
  "name": "Ali",
  "surname": "Aliyev"
}



